# Generated by Django 3.2.8 on 2021-11-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rom',
            new_name='Room',
        ),
    ]
