# Generated by Django 3.2.8 on 2021-11-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20211102_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
    ]
