# Generated by Django 3.2.8 on 2021-11-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-modify']},
        ),
    ]
