# Generated by Django 3.2.8 on 2021-11-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-modify']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
    ]
