# Generated by Django 3.2.8 on 2021-11-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20211102_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
