# Generated by Django 3.2.8 on 2021-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_room_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
