# Generated by Django 3.2.8 on 2021-11-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
